### ISSUE TITLE
why do you use Zeebe

### ISSUE THREAD

**Issue by fizz12344321** [andrejpetras/quarkus-insights-zeebe#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Zeebe in your project instead of others like Camunda, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Zeebe instead of your project instead of others like Camunda

**Comment by andrejpetras** [comment]
@fizz12344321 I think there is a misunderstanding. Zeebe is an open source cloud workflow engine from Camunda. It is the heart of the Camunda Platform 8. https://camunda.com/platform/zeebe/

Another interesting option for Quarkus could be Kogito. https://kogito.kie.org/

But from my experience I believe Zeebe's (Camunda Platform 8) architecture makes more sense.
